use master

go
drop database DB_2Q

go
create database DB_2Q

go
use DB_2Q

GO
create table TB_POSICIONAMENTO(
	ID_POSICAO INT IDENTITY(1,1) CONSTRAINT PK_TB_POSICIONAMENTO PRIMARY KEY,
	DS_POSICAO VARCHAR (100) NOT NULL	
)

go
create table TB_ESTADIO(
	ID_ESTADIO INT IDENTITY(1,1) CONSTRAINT PK_TB_ESTADIO PRIMARY KEY,
	DS_ESTADIO VARCHAR (100) NOT NULL,
	DS_CIDADE VARCHAR (100) NOT NULL,
	DS_CAPACIDADE INT NOT NULL	
)

go
CREATE TABLE TB_JOGADOR
( 
	ID_JOGADOR INT IDENTITY(1,1) CONSTRAINT PK_TB_JOGADOR PRIMARY KEY,
	ID_POSICIONAMENTO INT NULL CONSTRAINT FK_TB_JOGADOR_TB_POSICIONAMENTO FOREIGN KEY REFERENCES TB_POSICIONAMENTO(ID_POSICAO),
	DE_NOME VARCHAR(100),	
	DT_NASCIMENTO DATETIME,
	NR_CAMISA INT,
	DT_CONVOCACAO DATETIME,
	DT_DISPENSA DATETIME,
)

INSERT INTO TB_POSICIONAMENTO VALUES ('Goleiro');
INSERT INTO TB_POSICIONAMENTO VALUES ('Lateral Esquerdo');
INSERT INTO TB_POSICIONAMENTO VALUES ('Goleiro Direito');
INSERT INTO TB_POSICIONAMENTO VALUES ('Zagueiro');
INSERT INTO TB_POSICIONAMENTO VALUES ('Volante');
INSERT INTO TB_POSICIONAMENTO VALUES ('Meio Campo');
INSERT INTO TB_POSICIONAMENTO VALUES ('Atacante');


INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio Lujniki', 'Moscou', 81000)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Arena Otkrytie (Estádio Spartak)', 'Moscou', 45360)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio Krestovsk (Estádio de São Petersburgo)', 'São Petersburgo', 68134)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio de Kaliningrado', 'Kaliningrado', 35212)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Arena Kazan', 'Kazan', 45105)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio de Níjni Novgorod', 'Níjni Novgorod', 44899)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio de Samara', 'Samara', 44918)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Arena Volgogrado', 'Volgogrado', 44015)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Arena Mordovia', 'Saransk', 45015)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Arena Rostov', 'Rostov do Don', 43702)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio Olímpico de Fisht', 'Sóchi', 47659)
INSERT INTO TB_ESTADIO (DS_ESTADIO, DS_CIDADE,  DS_CAPACIDADE) VALUES ('Estádio Central', 'Ecaterimburgo', 44130)

select * from TB_POSICIONAMENTO

select * from TB_ESTADIO

SELECT a.ID_JOGADOR, a.ID_POSICIONAMENTO, a.DE_NOME, a.DT_NASCIMENTO, 
a.NR_CAMISA, a.DT_CONVOCACAO, a.DT_DISPENSA, b.DS_POSICAO 
FROM TB_JOGADOR a 
INNER JOIN TB_POSICIONAMENTO b ON a.ID_POSICIONAMENTO = b.ID_POSICAO 


